/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_local_Configurations_SnapConfiguration */

#ifndef _Included_org_local_Configurations_SnapConfiguration
#define _Included_org_local_Configurations_SnapConfiguration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_local_Configurations_SnapConfiguration
 * Method:    positionWindowInCorner
 * Signature: (IIIII)Lorg/local/model/WindowPosition;
 */
JNIEXPORT jobject JNICALL Java_org_local_Configurations_SnapConfiguration_positionWindowInCorner
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_local_Configurations_SnapConfiguration
 * Method:    positionWindowInHalf
 * Signature: (IIIII)Lorg/local/model/WindowPosition;
 */
JNIEXPORT jobject JNICALL Java_org_local_Configurations_SnapConfiguration_positionWindowInHalf
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
